logfile: pdp.log
authorized: 
  - auth_key: "NCNRTOKEN"
    user:     "gurn"
    client:    "ncnr"
  - auth_key: "DRAFTTOKEN"
    user:     "draft"
    client:    "test"

conventions: 
  pdp0:
    clients: 
      ncnr: 
        default_shoulder: "ncnr0"
        localid_provider: True
        auth_key: "NCNRdev"
      default: 
        default_shoulder: "pdp0"
        localid_provider: False
        auth_key: "MIDASdev"

    shoulders: 
      ncnr0: 
        allowed_clients: [ "ncnr" ]
        bagger: 
          override_config_for: "pdp0"
          factory_function: "nistoar.pdr.publish.service.pdp.PDPBaggerFactory"
          assign_doi: "always"
        id_minter: 
          naan: "88434"
          based_on_sipid: True
          sequence_start: 21

      pdp0:
        allowed_clients: [ "test" ]
        bagger:
          bag_builder:
            validate_id: True
            init_bag_info:
              NIST-BagIt-Version: "X.3"
              Organization-Address: ["100 Bureau Dr.", "Gaithersburg, MD 20899"]
            ensure_nerdm_type_on_add: "https://data.nist.gov/od/dm/nerdm-schema/v0.6"
          doi_naan: "10.18434"
          finalize:
          repo_base_url: "https://test.pdr.net/"
          
        id_minter: 
          naan: "88434"
          sequence_start: 17

