logfile: midas-dmp.log
dbio:
   factory:  fsbased
about: 
   title: "MIDAS Authoring Services"
   describedBy: "https://midas3.nist.gov/midas/apidocs"
   href: "http://midas3.nist.gov/midas/dmp"
services: 
   dmp: 
      about: 
         message:     "DMP Service is available"
         title:       "Data Management Plan (DMP) Authoring API"
         describedBy: "https://midas3.nist.gov/midas/apidocs"
         href:        "http://midas3.nist.gov/midas/dmp"

      broker: 
         clients: 
             midas: 
                default_shoulder: mdm1
             default: 
                default_shoulder: mdm1

      dbio: 
         superusers:                [ "rlp3" ]
         allowed_project_shoulders: ["mdm0", "mdm1"]
         default_shoulder:          mdm1

      default_convention: mdm1
      conventions: 
         mdm1: 
            about: 
                title:       "Data Management Plan (DMP) Authoring API (mdm1 convention)"
                describedBy: "https://midas3.nist.gov/midas/apidocs/dmp/mdm1"
                href:        "http://midas3.nist.gov/midas/dmp/mdm1"
                version:     mdm1
