logfile: midas.log
loglevel: DEBUG
dbio:
   factory:  fsbased
about: 
   title: "MIDAS Authoring Services"
   describedBy: "http://localhost:9091/midas/docs"
   href: "http://localhost:9091/midas/"
services: 
   dap:
      about: 
         message:     "DMP Service is available"
         title:       "Digital Asset Publication (DAP) Authoring API"
         describedBy: "http://localhost:9091/docs/dapsvc-elements.html"
         href:        "http://localhost:9091/midas/dap"

      clients: 
         midas: 
            default_shoulder: mdsx
         default: 
            default_shoulder: mdsx

      dbio: 
         superusers:                [ "rlp3" ]
         allowed_project_shoulders: ["mdsx", "mds3", "mds0", "pdr0"]
         default_shoulder:          mdsx

      include_headers:
         "Access-Control-Allow-Origin": "*"

      default_convention: mdsx
      conventions: 
         mdsx: 
            about: 
                title:       "Digital Asset Publication (DAP) Authoring API (mds3 convention)"
                describedBy: "http://localhost:9091/docs/dapsvc-elements.html"
                href:        "http://localhost:9091/midas/dap/mdsx"
                version:     mdsx
            assign_doi: always
            doi_naan:   "18434"

   dmp: 
      about: 
         message:     "DMP Service is available"
         title:       "Data Management Plan (DMP) Authoring API"
         describedBy: "http://localhost:9091/docs/dmpsvc-elements.html"
         href:        "http://localhost:9091/midas/dmp"

      clients: 
          midas: 
             default_shoulder: mdm1
          default: 
             default_shoulder: mdm1

      dbio: 
         superusers:                [ "rlp3" ]
         allowed_project_shoulders: ["mdm0", "mdm1"]
         default_shoulder:          mdm1

      include_headers:
         "Access-Control-Allow-Origin": "*"

      default_convention: mdm1
      conventions: 
         mdm1: 
            about: 
                title:       "Data Management Plan (DMP) Authoring API (mdm1 convention)"
                describedBy: "http://localhost:9091/docs/dmpsvc-elements.html"
                href:        "http://localhost:9091/midas/dmp/mdm1"
                version:     mdm1
