name: testall
on:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore: ['main', 'integration']
    paths:
      - 'docker/**'
      - '.github/workflows/**'
jobs:
  testall:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Containers
        env:
          OAR_DOCKERHUB_CRED: ${{ secrets.OAR_DOCKERHUB_CRED }}
        run: |
          bash scripts/dhsetup.sh
          cd docker && bash ./dockbuild.sh

      - name: Build & Run Python Tests via Docker
        run: scripts/testall.docker python

